draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_set_font(font_little);
draw_set_alpha(alpha);
draw_set_color(c_yellow);
draw_text(780,670,string_hash_to_newline(n));
draw_set_font(font_littleLess);
draw_set_color(c_white);
draw_text(780,700,string_hash_to_newline(n_info));